version: 2
updates:
  - package-ecosystem: bundler
    directory: "/"
    schedule:
      interval: monthly
      time: "08:00"
      timezone: America/New_York
    open-pull-requests-limit: 10
    ignore:
      # Drops support for Ruby 2.5
      - dependency-name: pry-stack_explorer
        versions:
          - ">= 5.0"
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: monthly
      time: "08:00"
      timezone: America/New_York
    open-pull-requests-limit: 10
