require:
  - rubocop-performance

AllCops:
  NewCops: disable
  TargetRubyVersion: 2.5
  Include:
    - "**/*.rb"
    - "**/Rakefile"
    - "**/Gemfile"
    - "**/config.ru"
  Exclude:
    - "vendor/**/*"
    - "**/tmp/**/*"
    - "middleman-cli/lib/middleman-cli/templates/**/*"

Style/FrozenStringLiteralComment:
  Enabled: true
  EnforcedStyle: always

Security/YAMLLoad:
  Enabled: false
Style/GuardClause:
  Enabled: false
Layout/LineLength:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Style/Documentation:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
Metrics/ModuleLength:
  Enabled: false
Metrics/PerceivedComplexity:
  Enabled: false
Metrics/ClassLength:
  Enabled: false
Lint/AmbiguousRegexpLiteral:
  Enabled: false
Lint/AmbiguousBlockAssociation:
  Enabled: false
Lint/UriEscapeUnescape:
  Enabled: false
Lint/SuppressedException:
  Enabled: false
Lint/ShadowedException:
  Enabled: false
Naming/FileName:
  Enabled: false
Naming/MethodParameterName:
  Enabled: false
Naming/MemoizedInstanceVariableName:
  Enabled: false
Naming/HeredocDelimiterNaming:
  Enabled: false
Security/Eval:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false
Style/MissingRespondToMissing:
  Enabled: false
Lint/MissingSuper:
  Enabled: false
Lint/EmptyFile:
  Enabled: false
Style/EvalWithLocation:
  Enabled: false
Style/ClassVars:
  Enabled: false
Style/GlobalVars:
  Enabled: false
Style/Proc:
  Enabled: false
Style/OptionalBooleanParameter:
  Enabled: false
Style/AccessorGrouping:
  Enabled: false
Style/RedundantRegexpEscape:
  Enabled: false
Style/StringConcatenation:
  Enabled: false
Layout/RescueEnsureAlignment:
  Enabled: false
Style/CaseLikeIf:
  Enabled: false
Style/RedundantSelfAssignment:
  Enabled: false
Style/SoleNestedConditional:
  Enabled: false
Lint/RedundantSafeNavigation:
  Enabled: false