AllCops:
  Include:
    - '**/Rakefile'
    - '**/Gemfile'
    - '**/config.ru'
    - '**/gem_rake_helper.rb'
  Exclude:
    - 'script/**/*'
    - 'vendor/**/*'
    - '**/tmp/**/*'
    - '**/bin/**/*'
    - 'middleman-core/lib/middleman-core/step_definitions/**/*'
    - 'middleman-core/fixtures/**/*'
    - 'middleman-core/features/**/*'
    - 'middleman-core/spec/**/*'
    - 'middleman-cli/lib/middleman-cli/templates/**/*'
    - 'middleman-cli/fixtures/**/*'
    - 'middleman-cli/features/**/*'
    - 'middleman-cli/spec/**/*'
DoubleNegation:
  Enabled: false
LineLength:
  Enabled: false
MethodLength:
  Enabled: false
ClassLength:
  Enabled: false
Documentation:
  Enabled: false
HashSyntax:
  EnforcedStyle: ruby19
SpaceAroundEqualsInParameterDefault:
  EnforcedStyle: no_space
PerlBackrefs:
  Enabled: false
ClassAndModuleChildren:
  Enabled: false
AssignmentInCondition:
  Enabled: false
CyclomaticComplexity:
  Enabled: false
Lint/SuppressedException:
  Enabled: false
EndAlignment:
  EnforcedStyleAlignWith: variable
SignalException:
  Enabled: false
RegexpLiteral:
  Enabled: false
FormatString:
  Enabled: false
CaseIndentation:
  EnforcedStyle: end
TrivialAccessors:
  Enabled: false
SingleLineBlockParams:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Metrics/PerceivedComplexity:
  Enabled: false
Style/ParallelAssignment:
  Enabled: false
Style/BlockDelimiters:
  Enabled: false
Style/MultilineBlockChain:
  Enabled: false
Style/SpecialGlobalVars:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
