AllCops:
  Include:
    - '**/Rakefile'
    - '**/Gemfile'
    - '**/config.ru'
    - '**/gem_rake_helper.rb'
  Exclude:
    - 'script/**/*'
    - 'vendor/**/*'
    - '**/tmp/**/*'
    - '**/bin/**/*'
    - 'middleman-core/lib/middleman-core/step_definitions/**/*'
    - 'middleman-core/fixtures/**/*'
    - 'middleman-core/features/**/*'
    - 'middleman-core/spec/**/*'
    - 'middleman-cli/lib/middleman-cli/templates/**/*'
    - 'middleman-cli/fixtures/**/*'
    - 'middleman-cli/features/**/*'
    - 'middleman-cli/spec/**/*'

Layout/CaseIndentation:
  EnforcedStyle: end
Layout/EndAlignment:
  EnforcedStyleAlignWith: variable
Layout/LineLength:
  Enabled: false
Layout/SpaceAroundEqualsInParameterDefault:
  EnforcedStyle: no_space

Lint/AssignmentInCondition:
  Enabled: false
Lint/SuppressedException:
  Enabled: false

Metrics/AbcSize:
  Enabled: false
Metrics/ClassLength:
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Metrics/PerceivedComplexity:
  Enabled: false

Style/BlockDelimiters:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/DoubleNegation:
  Enabled: false
Style/FormatString:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Style/HashSyntax:
  EnforcedStyle: ruby19
Style/MultilineBlockChain:
  Enabled: false
Style/ParallelAssignment:
  Enabled: false
Style/PerlBackrefs:
  Enabled: false
Style/RegexpLiteral:
  Enabled: false
Style/SignalException:
  Enabled: false
Style/SingleLineBlockParams:
  Enabled: false
Style/SpecialGlobalVars:
  Enabled: false
Style/TrivialAccessors:
  Enabled: false
