source :rubygems

group :development do
  gem "cucumber", "~> 1.1.0"
  gem "aruba",    "~> 0.4.11"
  gem "rake",     "~> 0.9.2"
  gem "rspec",    "~> 2.7"
  gem "rdoc",     "~> 3.9"
  # gem "yard"
end
  
group :test do
  # For actual tests
  gem "sinatra"
  gem "slim"
  gem "coffee-filter", "~> 0.1.1"
  gem "liquid", "~> 2.2"
  gem "jquery-rails", "~> 2.0.1"
  # gem "bootstrap-rails", "0.0.5"
  # gem "zurb-foundation"
end

gem "middleman-core", :path => "middleman-core"
gem "middleman-more", :path => "middleman-more"
gem "middleman", :path => "middleman"
gem "compass", "~> 0.11.0"