Feature: Tilt missing support libraries

  Scenario: Rendering Textile and Wiki files
    Given the Server is running at "missing-tilt-library-app"
    When I go to "/danger-zone/more-wiki.html.wiki"
    Then I should see "File Not Found"
    When I go to "/danger-zone/more-wiki.html"
    Then I should see "File Not Found"
    When I go to "/safe-zone/my-wiki.html.wiki"
    Then I should see "Safe"
    When I go to "/safe-zone/my-wiki.html"
    Then I should see "File Not Found"
    When I go to "/textile-source.html.textile"
    Then I should see "File Not Found"
    When I go to "/textile-source.html"
    Then I should see "File Not Found"
    When I go to "/wiki-source.html.wiki"
    Then I should see "Hola"
    When I go to "/wiki-source.html"
    Then I should see "File Not Found"